version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    restart: always

  mysql:
      image: mysql:8.0
      container_name: dq-mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: data_quality
        MYSQL_USER: dquser
        MYSQL_PASSWORD: 1234
      ports:
        - "3306:3306"
      volumes:
        - dq-mysql-data:/var/lib/mysql
        - ./mysql/init:/docker-entrypoint-initdb.d

volumes:
  dq-mysql-data:


